spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASS}

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USER}
        password: ${MAIL_PASS}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
