spring:
  application:
    name: Day5_Validation

  datasource:
    url: jdbc:mysql://localhost:3306/day5_validation?createDatabaseIfNotExist=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true