spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dtn_thymeleaf?createDatabaseIfNotExist=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true

    properties:
      hibernate:
        format_sql: true



