spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dtn_security_prod?createDatabaseIfNotExist=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none # thay đổi entity cũng không tự gen database
